FORMAT: 1A
HOST: https://api.hootsuite.com/api/2

# Engagement API V3

SCUM Facade API V3

# Data Structures

## Message (object)
+ sourceNetwork: YouTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ title: Message Title (string, optional) - Title of the message. 
+ body: Message body goes here. (string, required) - Body of the message.

## ProfileSummary (object)
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ profileId: 1234abc (string, required)
+ name: Bob (string, optional)
+ avatarUrl: `http://www.youtube.com/user123`(string, optional)

## Link (object)
+ url: http://link.test (string, required) - URL that the link is pointing to.
+ title: My link name (string, optional) - Display text for the link.
+ description: My link description (string, optional) - Description of the link. 
+ previewImageUrl: http://preview.fake/preview.jpg (string, optional) - URL of image preview.
+ includeImagePreview: true (boolean, optional) - Whether to show the preview image.

## Video (object)
+ embedUrl: www.youtube.com/embed/ASDfjkzf (string, optional) - URL to an embeddable video.
+ sourceUrl: www.youtube.com/ASDLJLAasd (string, optional) - URL to source video
+ videoId: ADLKJsdfsl3 (string, optional) - Video ID
+ previewImageUrl (string, optional) - Preview image URL

## Image (object)
+ url: http://url.to.image/image.jpg (string, required) - URL to this image.

## Media (object)
+ links (array[Link], optional) - Any links in the post.
+ images (array[Image], optional) - Any images in the post.
+ videos (array[Video], optional) - Any videos in the post.

## Statistic (object)
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ type: likes (enum[string], required) - type of statistics ['likes', 'dislikes', 'replies', 'views']
+ value (string, required) - value

## Status (object)
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ type: videoStatus (string, required) - type of status
+ statusValue (string, required) - actual status ['deleted', 'failed', 'processed', 'rejected', 'uploaded']
+ statusDescription (string, optional) - additional description

## Tag (object)
+ sourceNetwork: youTube (enum[string], required) - ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ name (string, required) - actual tag

## Position (object)
+ latitude: 20.123 (number, required) - Latitude of this position.
+ longitude: 40.123 (number, required) - Longitude of this position.

## Place (object)
+ sourceNetwork: youTube (enum[string], required) - ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ resourceType: page (enum[string], required)
+ resourceId: asdfzv (string, required) 

## Location (object)
+ position (Position, optional) - Position metadata. 
+ place (Place, optional) - Place metadata.

## Privacy (object)
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ scope: public (enum[string], required) - ['public', 'directconnections', 'directandsecondaryconnections', 'private', 'unlisted']
+ scopeIdSet (array[string], optional) - array of ids related to scope restriction
+ hidden (boolean, optional)

## InReplyTo (object)
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ objectType: post (enum[string], required) - ['post', 'comment']
+ objectId: abcd12345 (string, required) - Id of the post or comment
+ post (Post, optional) - only set when objectType is a post

## Comment (object)
+ id: jksdfZJfiewrfVCW== (string, required) - ID of this comment.
+ inReplyTo (InReplyTo, required) - defines the parent
+ message (Message, required) - The message this comment contains.
+ author (ProfileSummary, required) - The author of this comment.
+ statistics (array[Statistic], required) - array of stats objects.
+ replies (array[Comment], optional) - only set when getting all comments for YT channel
+ media (Media, optional) - Any media contained within this comment.
+ privacy (Privacy, optional) - The privacy settings of this comment.
+ currentUserRating: none (enum[string], required) - Current user's own rating ['like', 'dislike', 'none'] 
+ moderationStatus: published (enum[string], required) - Comment moderation status ['heldforreview', 'published', 'likelyspam']
+ createdDate: 1450828522869 (string, required) - Unix epoch timestamp.

## CommentList (object)
+ comments (array[Comment], required) - actual comments
+ pagingResponse (PagingResponse, required) - paging

## Post (object)
+ id: zxcv1234 (string, required) - ID of the post of the social network.
+ sourceNetwork: youTube (enum[string], required) - source ['twitter', 'facebook', 'youTube', 'instagram', 'linkedIn', 'googlePlus']
+ message (Message, required) - Message of the post.
+ author (ProfileSummary, required)
+ statistics (array[Statistic], required) - Information about likes, shares, views, etc. for this post.
+ inReplyTo (InReplyTo, optional) - Information about the post this is replying to.
+ commentList (CommentList, optional) - Comments
+ media (Media, optional) - Media contained within this post.
+ location (Location, optional) - Location metadata about the post.
+ status (Status, optional) - Status of the post
+ tags (array[Tag], optional) - Post tags
+ privacy (Privacy, optional) - Privacy information about the post.
+ currentUserRating: like (enum[string], optional) - [like, dislike, none] Current user's own rating 
+ createdDate: 1450828522869 (string, required) - Unix epoch timestamp.

## PagingResponse (object)
+ nextPageToken: akjvzSDFijwefADSC== (string, optional) - Token used to retrieve the next page.
+ previousPageToken: WIDJFjkafF== (string, optional) - Token used to retrieve the previous page, if available.

## PostResults (object)
+ posts (array[Post], required) - Array of posts matching the stream type.
+ paging (PagingResponse, optional) - Paging information that can be used in subsequent requests.

## CommentsResults (object)
+ comments (array[Comment], required) - Array of comments for post or comment
+ paging (PagingResponse, optional) - Paging information that can be used in subsequent requests.


## Error (object)


## Posts [/posts]

### Get posts [GET /posts/{socialProfileId}{?type}{?pageSize}{?pageToken}]
+ Parameters
    + socialProfileId: 12344599 (string, required) - Social profile ID of the user performing this search.
    + type: Y_MY_CHANNEL (string, required) - Type of posts to be collected and returned. Valid values are:
        * Y_MY_CHANNEL - Posts from YouTube's My Channel. 
    + pageSize: 10 (number, optional) - number of posts per page
    + pageToken: 12ASD13sfdsf24 (string, optional) - Page token
        
+ Response 200 (application/json)
    + Attributes
        + request: /api/2/posts/150332989?type=Y_MY_CHANNEL
        + results (PostResults, required) - Result object
        + error (Error, required) - Error object

## Comments [/comments]

### Get comments [GET /comments/{socialProfileId}{?objectType}{?objectId}{?pageSize}{?nextPageToken}{?moderationStatus}]
+ Parameters
    + socialProfileId: 150332989 (string, required) - Social profile ID of the user performing this search. 
    + objectType: post (string, required) - Type of object to get the comments on ['post','comment']
    + objectId: 1231ASDwe (string, required) - Id of the object for which to get comments
    + pageSize: 10 (number, optional) - number of posts per page
    + nextPageToken: sdfjhkAD213fF (string, optional) - Page token
    + moderationStatus: posted (string, optional ) - Comment moderation status ['heldforreview', 'posted', 'likelyspam']

+ Response 200 (application/json)
    + Attributes
        + request: /api/2/comments/150332989?objectType=post&objectId=RTHX5qDff3Q
        + results (CommentsResults, required) - Result object
        + error (Error, required) - Error object

### Post comment [POST /comments/{socialProfileId}]
+ Parameters
    + socialProfileId: 123123123 (string, required) - Social profile ID of the user performing this search. 

+ Request body (application/json)
    + Attributes
        + objectType: post (string, required) - Type of object to get the comments on ['post','comment']
        + objectId: 1XFsd12 (string, required) - Id of the object for which to get comments
        + message: test message (string, required) - Comment message to be posted

+ Response 200 (application/json)
    + Attributes
        + request: /api/2/comments/150332989
        + results (Comment, required) - Result object
        + error (Error, required) - Error object